// <auto-generated />
using System;
using DataAccessLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(RealEstateDBContext))]
    [Migration("20231219182601_mig-3")]
    partial class mig3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Alici", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MailAdresi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TelefonNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TelefonNo.");

                    b.HasKey("Id");

                    b.ToTable("Alicilar", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Arsa", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("AdaNo")
                        .HasColumnType("int")
                        .HasColumnName("AdaNo.");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<bool>("ImarDurumu")
                        .HasColumnType("bit")
                        .HasColumnName("Imar durumu");

                    b.Property<bool>("KatKarsiliginaUygun")
                        .HasColumnType("bit");

                    b.Property<string>("Kimden")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("KrediyeUygun")
                        .HasColumnType("bit");

                    b.Property<int>("Metrekare")
                        .HasColumnType("int");

                    b.Property<decimal?>("MetrekareFiyat")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int>("PaftaNo")
                        .HasColumnType("int")
                        .HasColumnName("PaftaNo.");

                    b.Property<int>("ParselNo")
                        .HasColumnType("int")
                        .HasColumnName("ParselNo.");

                    b.Property<string>("SatilikKiralik")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Arsa", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Daire", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Aidat")
                        .HasColumnType("int");

                    b.Property<bool?>("Asansor")
                        .HasColumnType("bit");

                    b.Property<int?>("BalkonSayisi")
                        .HasColumnType("int");

                    b.Property<int?>("BanyoSayisi")
                        .HasColumnType("int");

                    b.Property<int?>("BinaYasi")
                        .HasColumnType("int");

                    b.Property<int?>("BulunduguKat")
                        .HasColumnType("int");

                    b.Property<bool>("EsyaliMi")
                        .HasColumnType("bit");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Isıtma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("KatSayisi")
                        .HasColumnType("int");

                    b.Property<bool?>("KrediyeUygun")
                        .HasColumnType("bit");

                    b.Property<string>("KullanimDurumu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MetrekareBrut")
                        .HasColumnType("int");

                    b.Property<int>("MetrekareNet")
                        .HasColumnType("int");

                    b.Property<int>("OdaSayisi")
                        .HasColumnType("int");

                    b.Property<bool?>("Otopark")
                        .HasColumnType("bit");

                    b.Property<string>("SatilikKiralik")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("SiteMi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Daire", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Depo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("AdaNo")
                        .HasColumnType("int")
                        .HasColumnName("AdaNo.");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int>("Metrekare")
                        .HasColumnType("int");

                    b.Property<int>("MetrekareFiyat")
                        .HasColumnType("int");

                    b.Property<int>("ParselNo")
                        .HasColumnType("int")
                        .HasColumnName("ParselNo.");

                    b.Property<string>("SatilikKiralik")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Depo", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Dukkan", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Aidat")
                        .HasColumnType("int");

                    b.Property<bool?>("Asansor")
                        .HasColumnType("bit");

                    b.Property<int?>("BalkonSayisi")
                        .HasColumnType("int");

                    b.Property<int?>("BanyoSayisi")
                        .HasColumnType("int");

                    b.Property<int>("BinaYasi")
                        .HasColumnType("int");

                    b.Property<int?>("BulunduguKat")
                        .HasColumnType("int");

                    b.Property<bool>("EsyaliMi")
                        .HasColumnType("bit");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Isıtma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("KatSayisi")
                        .HasColumnType("int");

                    b.Property<bool?>("KrediyeUygun")
                        .HasColumnType("bit");

                    b.Property<string>("KullanimDurumu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MetrekareBrut")
                        .HasColumnType("int");

                    b.Property<int?>("MetrekareNet")
                        .HasColumnType("int");

                    b.Property<int>("OdaSayisi")
                        .HasColumnType("int");

                    b.Property<bool?>("Otopark")
                        .HasColumnType("bit");

                    b.Property<string>("SatilikKiralik")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("SiteMi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Dukkan", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Ilan", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IlanTipi")
                        .HasColumnType("int");

                    b.Property<int>("Satici")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ilanlar", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.IlanTalepTipi", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("TipAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TipNo")
                        .HasColumnType("int")
                        .HasColumnName("TipNo.");

                    b.HasKey("Id");

                    b.ToTable("IlanTalepTipleri", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Satici", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MailAdresi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TelefonNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TelefonNo.");

                    b.HasKey("Id");

                    b.ToTable("Saticilar", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Talep", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Alici")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TalepTipi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Talepler", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Tarla", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("AdaNo")
                        .HasColumnType("int")
                        .HasColumnName("AdaNo.");

                    b.Property<bool>("ImarDurumu")
                        .HasColumnType("bit");

                    b.Property<bool>("KrediyeUygun")
                        .HasColumnType("bit");

                    b.Property<int>("Metrekare")
                        .HasColumnType("int");

                    b.Property<decimal?>("MetrekareFiyat")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int>("PafaNo")
                        .HasColumnType("int")
                        .HasColumnName("PafaNo.");

                    b.Property<int>("ParselNo")
                        .HasColumnType("int")
                        .HasColumnName("ParselNo.");

                    b.Property<string>("SatilikKiralik")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TapuDurumu")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Tarla", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("EntityLayer.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EntityLayer.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EntityLayer.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("EntityLayer.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EntityLayer.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
